
name: volume-group-operator-ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build_and_push_images:
    name: "Build and push images"
    runs-on: ubuntu-latest
    env:
      volume_group_operator_repository: volume-group-operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Build and push volume-group-operator
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: false
          tags: |
            $volume_group_operator_repository:test_volume_group
            $volume_group_operator_repository:test_volume_group2
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
