
name: volume-group-operator-ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  build_and_push_images:
    name: "Build and push images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: ['operator']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Build and push ${{ matrix.image_type }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: false
          tags: |
            ${{ secrets.CSIBLOCK_DOCKER_REGISTRY_USERNAME }}/ibm-block-csi-${{ matrix.image_type }}:test_volume_group
            ${{ secrets.CSIBLOCK_DOCKER_REGISTRY_USERNAME }}/ibm-block-csi-${{ matrix.image_type }}:test_volume_group2
          file: build/Dockerfile.${{ matrix.image_type }}
          cache-from: type=local,src=/tmp/.buildx-${{ matrix.image_type }}
          cache-to: type=local,dest=/tmp/.buildx-new-${{ matrix.image_type }}
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896