
name: volume-group-operator-ci
on:
  push:
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  build_and_push_images:
    name: "Build and push images"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Build and push volume-group-operator
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/ppc64le,linux/s390x
          push: false
          tags: |
            ibm-block-csi-volume-group-operator:test_volume_group
            ibm-block-csi-volume-group-operator:test_volume_group2
          file: Dockerfile
          cache-from: type=local,src=/tmp/.buildx-volume-group-operator
          cache-to: type=local,dest=/tmp/.buildx-new-volume-group-operator
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896